fix:弹窗数据错误
soybeanjs/soybean-admin-antd pull request #31
Opened 2024-06-25 03:35 UTC by YBY2020

发现系统管理模块中，普遍存在打开弹窗后数据对应不上的问题（只有第一次打开弹窗的数据是正常的），小小修复了一下

2024-06-25 03:39 UTC, honghuangdc commented
请先提个issues描述下具体错误
另外这个解法太粗暴了，最好不要用v-if去绑定弹窗组件，除了会影响弹窗本身的动画效果，另外每次打开都重新渲染带来没有必要的开销

2024-06-25 03:40 UTC, honghuangdc commented
另外，提交请按照规范提交commit，最好用英文提交

2024-06-25 03:42 UTC, Azir-11 requested changes
1. commit信息错误
2. 问题未描述清晰，建议先提issue
3. 代码质量不通过

2024-06-26 11:01 UTC, honghuangdc commented
已修复 740d6f5

2024-06-26 11:02 UTC, closed without merging